### ISSUE TITLE
BayEOSSender: catch all errors

### ISSUE THREAD

**Issue by holzheu** [kleebaum/bayeosgatewayclient#1]
While upgrading the gateway we noticed that the sender thread terminated unexpectedly. The writer was still running. Unfortunately we do not have a error message.

Would it help to set up a 

<pre>
            try:
                res = self.send()
                if res > 0:
                    print 'Successfully sent ' + str(res) + ' frames.'
            except:
                sys.stderr.write('Unexpected send error in run()\n')
</pre>

in the run() method?

**Comment by oarchner** [comment]
Added in c0640bb2ed7e5e4c1c5484359300698342b25e0b

**Comment by kleebaum** [comment]
Thanks, I updated this.
